### ISSUE TITLE
"Done" issue

### ISSUE THREAD

**Issue by dietpanda** [evankrummel/irony_bot#5]
After Submitting Documents when writing "done" but either seems to shut down or die. It might have been an interval shut down in which I missed. Or maybe bot just stopped running at that time, either way i'm not quite sure but this is what i have found

**Comment by evankrummel** [comment]
Can you please provide screenshots of the conversation as well as the message ID of your "done" message? @dietpanda

**Comment by evankrummel** [comment]
Thanks for your issue submission.  We've tried to recreate this issue in multiple different ways and we can't seem to get it to happen again.  I'll close this issue for now, but please feel free to open a new issue if you have it happen again.  
Thanks!
